### ISSUE TITLE
Support for Non-linear constraints / objective

### ISSUE THREAD

**Issue by freemin7** [tkoolen/Parametron.jl#111]
Hey,

after skimming the documentation and the source code i could find no reference to generic non-linear optimization, is that on purpose, did i miss something or wasn't it required yet in your applications?

**Comment by boranzhao** [comment]
I have the same question.

**Comment by freemin7** [comment]
I gained some more insight into the JuMP ecosystem. All the non linear stuff is currently handled by an oracle you call for function values, gradients and hessians.
So JuMP handles non-linear, non-quadratic terms very neglected and that might be fixed JuMP 2.0.
If someone from the team can confirm this, this would be great

**Comment by tkoolen** [comment]
Sorry about the response time. I'm afraid nonlinear constraints / objectives are out of scope for Parametron. The main driving force for this package's development was the need for a way to very quickly solve a series of linear or quadratic programs with the same sparsity pattern, which JuMP didn't offer.

> All the non linear stuff is currently handled by an oracle you call for function values, gradients and hessians.

I don't think that's completely fair. https://jump.dev/JuMP.jl/v0.21.1/nlp/ shows how JuMP is able to automatically differentiate the objective and constraint functions you give it, and `@NLparameter` can now be used to achieve similar warm starting / cheap problem modification behavior to what this package offers (though I'm not sure if they've gone to the same lengths to try to avoid allocations). In my experience, vector-valued constraint functions were always a bit of a hassle to implement in JuMP, but it's not impossible to work around.

**Comment by freemin7** [comment]
I understand that NLP isn't in scope for Parametron then. This is fair.

> All the non linear stuff is currently handled by an oracle you call for function values, gradients and hessians

Should probably have said 

> All the non linear stuff is currently handled by an oracle you call for objective values, constraint value, gradient of constraints and hessian of the Laplacian.

for an more accurate picture. I will look into the warm starting capabilities and program modification as i might want to make that functionality available from solvers I'm wrapping.
