### ISSUE TITLE
Compatibility with the new MOI modification API

### ISSUE THREAD

**Issue by rdeits** [tkoolen/Parametron.jl#24]
It looks like constraint modification changed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/388 , and that broke SimpleQP's interface (I noticed this because the compatible version of Gurobi.jl needs MOI master). @tkoolen are you already working on this or is that something i can help with?

**Comment by tkoolen** [comment]
Sure, if you'd like to help, that would be very welcome. I guess since tests rely on OSQP, that's probably the first thing to fix (note that it currently upper-bounds MOI).

https://github.com/oxfordcontrol/OSQP.jl/blob/master/src/MathOptInterfaceOSQP.jl

**Comment by rdeits** [comment]
Ok, I'll give it a shot. 

Edit: https://github.com/oxfordcontrol/OSQP.jl/pull/19
