### ISSUE TITLE
Consider allowing interpolation into a constraint/expression/etc.

### ISSUE THREAD

**Issue by rdeits** [tkoolen/Parametron.jl#30]
I've noticed that because everything inside an `@constraint()` call gets LazyExpression-wrapped, there are some weird issues with referential transparency. For example, this fails: 

```julia
x = Variable(model)
@constraint model [x] <= [0.]
```

with `ArgumentError: Unhandled expression head: vect.`. But this works: 

```julia
x = Variable(model)
lhs = [x]
rhs = [0.]
@constraint model lhs <= rhs
```

I realize this is a necessary result of the whole expression-wrapping stuff, but it would be nice to be able to work around it for things that don't actually need to be lazy-ified. 

We could do that by supporting `$` as a way to mark expressions which should just be evaluated rather than being wrapped. That would look like: 

```julia
@constraint model $([x]) <= $([0.])
```

Here's a sample implementation of the macro that preserves any `$`-interpolated expressions rather than wrapping them: 

```julia
lazy_wrap(x) = esc(x)

function lazy_wrap(x::Expr)
    if x.head == :line
        return esc(x)
    elseif x.head == :$ && length(x.args) == 1
        return esc(x.args[1])
    elseif x.head ∈ [:call, :block]
        x.args .= lazy_wrap.(x.args)
        if x.head == :call
            return :(wrap(SimpleQP.optimize_toplevel(SimpleQP.LazyExpression($(x.args...)))))
        else
            return esc(x)
        end
    else
        buf = IOBuffer()
        dump(buf, x)
        msg =
            """
            Unhandled expression head: $(x.head). expr:
            $(String(take!(buf)))
            """
        return :(throw(ArgumentError($msg)))
    end
end


macro expression(expr)
    lazy_wrap(expr)
end
```

(I couldn't figure out how to do this with `postwalk` cleanly, sadly)

**Comment by rdeits** [comment]
Or, alternatively, we could just support `vcat` expressions.

But I think there really may be cases where a user wants to splice in a value, rather than an expression. For example, I was just starting to write a simple controller, and i wanted to do: 

```julia
@constraint model qnext <= collect_joint_position_upper_bounds(mechanism)
```

but I don't actually want to collect those bounds every time I update the model. I just want to set them once at setup time.

**Comment by tkoolen** [comment]
Sure, sounds good. Feel free to open a PR. Don't do this though: `x.args .= lazy_wrap.(x.args)`; just create a new expression. And note that `@capture` from MacroTools also escapes the captured argument and functions, so you have to do that manually if you're not using `@capture` anymore. Why doesn't `postwalk` work for this?

**Comment by rdeits** [comment]
`postwalk` works from the leaves inward, but I need to stop any processing from happening on any expression which is descended from a `$` expression. So we could use `prewalk`, which goes from the root out to the leaves, but `prewalk` automatically recurses into the returned expression, which again isn't what we want here.

**Comment by tkoolen** [comment]
Ah, I see. Makes sense.

**Comment by tkoolen** [comment]
I can actually no longer reproduce the problem in the issue description:

```julia
julia> model = Model(optimizer)
Model{Float64, OSQP.MathOptInterfaceOSQP.OSQPOptimizer}(…)

julia> @constraint model [x] <= [0.] # fine

julia> SimpleQP.findallocs(model.nonposconstraints[1].expr) # doesn't allocate
LazyExpression{FunctionWrapper{…}(LazyExpression{Base.#copy!, …}(…))}(…): 0 bytes
  [1]: Array{SimpleQP.Functions.AffineFunction{Float64},1}
  [2]: LazyExpression{FunctionWrapper{…}(LazyExpression{SimpleQP.Functions.#vecsubtract!, …}(…))}(…): 0 bytes
    [1]: Array{SimpleQP.Functions.AffineFunction{Float64},1}
    [2]: LazyExpression{FunctionWrapper{…}(LazyExpression{Base.#identity, …}(…))}(…): 0 bytes
      [1]: Array{SimpleQP.Functions.Variable,1}
    [3]: LazyExpression{FunctionWrapper{…}(LazyExpression{Base.#identity, …}(…))}(…): 0 bytes
      [1]: Array{Float64,1}
```

Given https://github.com/tkoolen/SimpleQP.jl/pull/37#discussion_r198310568, I think https://github.com/tkoolen/SimpleQP.jl/pull/37 may not be necessary?

**Comment by tkoolen** [comment]
Feel free to reopen if #40 turns out to not be enough.
