### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by rdeits** [tkoolen/Parametron.jl#38]
It's time :wink: 

I think "SimpleQP" is underselling how useful this package is (and not necessarily accurate if we decide to add MIPs in the future). 

* ParametricOptimization.jl
* ParameterizedOptimization.jl
* ParameterizedOpt.jl
* ParOpt.jl
* LazyModels.jl
* OptimizationExpressions.jl (or something shorter like OptEx.jl?) 
* some awkward backronym derived from a word similar to "jump"
* Something else entirely (maybe just a *name*, like Gadfly, rather than a descriptive title)

**Comment by tkoolen** [comment]
Still don't know. I think I like ParameterizedOptimization or ParameterizedOpt the best so far, but I don't really like those either.

**Comment by rdeits** [comment]
Heh, yeah, I don't love the idea of typing those names out in full over and over. ParOpt.jl ?

**Comment by tkoolen** [comment]
ParFamOpt.jl, for parameterized families of optimization problems? Bonus is that this currently gives zero results on google.

**Comment by tkoolen** [comment]
Parametron (actually the Greek root for parameter)? Parametropt?

**Comment by rdeits** [comment]
Heh, I kinda like Parametron.jl

**Comment by rdeits** [comment]
Ok, last chance before I start writing this into the slides

**Comment by tkoolen** [comment]
Alright, Parametron it is.
