### ISSUE TITLE
Field access causes allocations

### ISSUE THREAD

**Issue by rdeits** [tkoolen/Parametron.jl#42]
Accessing fields inside an `@expression` causes allocation, as we end up transforming `x.y` into `getfield(x, :y)`, which can't be inferred (at least in 0.6). For example: 

```julia
frame = CartesianFrame3D()
model = SimpleQP.MockModel()
p = Parameter(model) do
    Point3D(frame, 0., 0., 0.)
end
expr = @expression p.v
SimpleQP.findallocs(expr)
```

gives: 

```
LazyExpression{FunctionWrapper{…}(LazyExpression{Core.#getfield, …}(…))}(…): 112 bytes
  [1]: Parameter{RigidBodyDynamics.Spatial.Point3D{StaticArrays.SArray{Tuple{3},Float64,1,3}}, …}(…): 48 bytes
  [2]: Symbol
```

We probably need to special-case `Core.getfield`.

**Comment by tkoolen** [comment]
Yeah; probably just have an optimization that turns it into a new `LazyExpression` with a little anonymous function as the head?

**Comment by rdeits** [comment]
Yup, will do

**Comment by tkoolen** [comment]
Fixed.
