### ISSUE TITLE
Dealing with FunctionWrappers

### ISSUE THREAD

**Issue by tkoolen** [tkoolen/Parametron.jl#76]
FunctionWrappers is still broken on 1.0, and telling people to check out the `tk/julia-0.7-quickfix` on my branch is not a real solution. I think to keep things moving for now we should just incorporate that version of FunctionWrappers into Parametron (it's just a single file). @rdeits, thoughts?

Ref: https://github.com/yuyichao/FunctionWrappers.jl/issues/8, https://github.com/JuliaLang/julia/issues/28669.

**Comment by rdeits** [comment]
Yeah, I think that's fine. I've done that in the past with e.g. https://github.com/rdeits/ConcreteInterfaces.jl/blob/master/src/ComputedFieldTypes/src/ComputedFieldTypes.jl
