### ISSUE TITLE
`:tuple` expressions not handled

### ISSUE THREAD

**Issue by rdeits** [tkoolen/Parametron.jl#88]
It looks like we're not currently handling `:tuple` expressions:

```julia
julia> using Parametron

julia> @expression(reshape(A, (2, 2)))
ERROR: ArgumentError: Unhandled expression head: tuple
Original expression
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol reshape
    2: Symbol A
    3: Expr
      head: Symbol tuple
      args: Array{Any}((2,))
        1: Int64 2
        2: Int64 2
Preprocessed expression
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol reshape
    2: Symbol A
    3: Expr
      head: Symbol tuple
      args: Array{Any}((2,))
        1: Int64 2
        2: Int64 2
Current expression:
Expr
  head: Symbol tuple
  args: Array{Any}((2,))
    1: Int64 2
    2: Int64 2
```

We can probably play the same trick we do with `vcat`, etc. and just preprocess `:tuple` expressions into a call to `Base.tuple(x.args...)`.

**Comment by tkoolen** [comment]
Yep, that seems like it should work.

It does seem like there's always one more case we need to handle specially. Maybe one of these weeks I'll get around to trying a Cassette-based implementation.

**Comment by tkoolen** [comment]
Feel free to tag a new release if you need one.

**Comment by rdeits** [comment]
No rush--the only time I came across this was in `reshape(A, (m, n))`, which already works fine as `reshape(A, m, n)`.
